apiVersion: v1
kind: Service
metadata:
  name: wcf-web-app-service
spec:
  selector:
    app: wcf-web-app
  ports:
  - protocol: "TCP"
    port: 5001
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcf-web-app
spec:
  selector:
    matchLabels:
      app: wcf-web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: wcf-web-app
    spec:
      containers:
      - name: wcf-web-app-centos7
        image: wcf-web-app-centos7:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000